// <auto-generated />
using System;
using DIO.Series.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DIO.Series.Data.Migrations
{
    [DbContext(typeof(ContextSeries))]
    partial class ContextSeriesModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DIO.Series.Domain.Entities.Episodio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("Excluido")
                        .HasColumnType("bit");

                    b.Property<int>("MinutosEpisodio")
                        .HasColumnType("int");

                    b.Property<string>("NomeEpisodio")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<int>("NumeroEpisodio")
                        .HasColumnType("int");

                    b.Property<Guid>("SerieId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Temporada")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SerieId");

                    b.ToTable("Episodio");
                });

            modelBuilder.Entity("DIO.Series.Domain.Entities.Serie", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Ano")
                        .HasColumnType("int");

                    b.Property<int>("Classificacao")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Elenco")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("Excluido")
                        .HasColumnType("bit");

                    b.Property<int>("Genero")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Temporadas")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Serie");
                });

            modelBuilder.Entity("DIO.Series.Domain.Entities.Episodio", b =>
                {
                    b.HasOne("DIO.Series.Domain.Entities.Serie", "Serie")
                        .WithMany("Episodios")
                        .HasForeignKey("SerieId")
                        .IsRequired();

                    b.Navigation("Serie");
                });

            modelBuilder.Entity("DIO.Series.Domain.Entities.Serie", b =>
                {
                    b.Navigation("Episodios");
                });
#pragma warning restore 612, 618
        }
    }
}
